name: Build Maximo App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller flask requests python-dotenv
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name=MaximoApp --add-data="frontend/templates;frontend/templates" --add-data="frontend/static;frontend/static" --add-data=".env;." --hidden-import=backend.auth.token_manager --hidden-import=backend.services.enhanced_profile_service --hidden-import=backend.services.enhanced_workorder_service --hidden-import=backend.api --hidden-import=dotenv app.py
    
    - name: Create distribution package
      run: |
        mkdir MaximoApp-Windows
        copy dist\MaximoApp.exe MaximoApp-Windows\
        echo # Maximo Configuration > MaximoApp-Windows\.env
        echo MAXIMO_BASE_URL=https://your-maximo-server.com/maximo >> MaximoApp-Windows\.env
        echo MAXIMO_API_KEY=your_api_key_here >> MaximoApp-Windows\.env
        echo MAXIMO_VERIFY_SSL=True >> MaximoApp-Windows\.env
        echo FLASK_SECRET_KEY=maximo_secret_key >> MaximoApp-Windows\.env
        echo APP_SECRET_KEY=app_secret_key >> MaximoApp-Windows\.env
        echo DEBUG=False >> MaximoApp-Windows\.env
        echo MAXIMO APPLICATION > MaximoApp-Windows\README.txt
        echo ================== >> MaximoApp-Windows\README.txt
        echo. >> MaximoApp-Windows\README.txt
        echo SETUP: >> MaximoApp-Windows\README.txt
        echo 1. Edit .env file with your Maximo server details >> MaximoApp-Windows\README.txt
        echo 2. Double-click MaximoApp.exe to run >> MaximoApp-Windows\README.txt
        echo 3. Application will open in your web browser >> MaximoApp-Windows\README.txt
    
    - name: Upload Windows build
      uses: actions/upload-artifact@v3
      with:
        name: MaximoApp-Windows
        path: MaximoApp-Windows/

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller flask requests python-dotenv
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name=MaximoApp --add-data="frontend/templates:frontend/templates" --add-data="frontend/static:frontend/static" --add-data=".env:." --hidden-import=backend.auth.token_manager --hidden-import=backend.services.enhanced_profile_service --hidden-import=backend.services.enhanced_workorder_service --hidden-import=backend.api --hidden-import=dotenv app.py
    
    - name: Create distribution package
      run: |
        mkdir MaximoApp-macOS
        cp dist/MaximoApp MaximoApp-macOS/
        chmod +x MaximoApp-macOS/MaximoApp
        cat > MaximoApp-macOS/.env << EOF
        # Maximo Configuration
        MAXIMO_BASE_URL=https://your-maximo-server.com/maximo
        MAXIMO_API_KEY=your_api_key_here
        MAXIMO_VERIFY_SSL=True
        FLASK_SECRET_KEY=maximo_secret_key
        APP_SECRET_KEY=app_secret_key
        DEBUG=False
        EOF
        cat > MaximoApp-macOS/README.txt << EOF
        MAXIMO APPLICATION
        ==================
        
        SETUP:
        1. Edit .env file with your Maximo server details
        2. Double-click MaximoApp to run
        3. Application will open in your web browser
        
        REQUIREMENTS:
        - No additional software needed
        - All dependencies included
        EOF
    
    - name: Upload macOS build
      uses: actions/upload-artifact@v3
      with:
        name: MaximoApp-macOS
        path: MaximoApp-macOS/
